---

stages:
  - lint

.lint-job:
  stage: lint
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
  image: python:3.12-alpine
  before_script:
    - apk add git
    - pip3 install -e .[dev]
  cache:
    paths:
      - '.cache/pip/'
  rules:
    - if: $LINTING_ENABLED == 'true'

ruff:
  extends: .lint-job
  script:
    ruff check saltbox_gateway # --select I --fix

mypy:
  extends: .lint-job
  script:
    mypy saltbox_gateway
