---

stages:
  - test  # Required by 'saltbox/ci-lib/def-branch-merge-guard.yml'
  - build
  - generate-scheme
  - generate-api-client
  - deploy


variables:
  # Set 0 to disable linting jobs
  LINTING_ENABLED: true


include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'


Build Gateway image for tag:
  stage: build
  extends: .build-image
  variables:
    TARGET: main
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build Gateway image for branch:
  stage: build
  extends: .build-image
  variables:
    TARGET: main
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'


.lint-job:
  stage: test
  variables:
    PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
    APK_CACHE_DIR: '$CI_PROJECT_DIR/.cache/apk'
  image: python:3.12-alpine
  before_script:
    - mkdir -p "$APK_CACHE_DIR"
    - apk add --cache-dir "$APK_CACHE_DIR" git
    - pip3 install -e .[dev]
  cache:
    paths:
      - '$PIP_CACHE_DIR'
      - '$APK_CACHE_DIR'
  rules:
    - if: $LINTING_ENABLED == 'true'


Ruff:
  extends: .lint-job
  script: ruff check saltbox_gateway  # --select I --fix


Mypy:
  extends: .lint-job
  script: mypy saltbox_gateway


Trigger API Client build:
  stage: build
  variables:
    SALTBOX_ENV_FILE: 'tests/test.env'
    MODULE_NAME: saltbox_gateway
    GEN_OPENAPI_CMD: python3 "./${MODULE_NAME}/utils/generate_openapi.py"
  trigger:
    include:
      - project: 'saltbox/ci-lib'
        file: 'gen-api-client.yml'
    strategy: mirror
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
