class JobException(Exception): ...


class JobDoesNotExistsException(JobException): ...


class JobMultipleReturnsException(JobException): ...


class JidError(RuntimeError): ...


class UnexpectedJidFormatError(JidError): ...


class UnexpectedDataFormatError(JidError): ...
